### ISSUE TITLE
Bleed, burn and poison.

### ISSUE THREAD

**Issue by chimiko** [ravahn/BnS_ACT_Plugin#18]
Hello,
I've been wondering if its possible to remove some abilitys from the meter.
Bleed, burn and poison to be exact. I mean you don't have to remove them but atleast make it possible to remove them from the pharses. Or maybe there already is but i don't know how too atleast.

Bleed, burn and poison (dot effects) overall tends to mess up the actual numbers alot since bleed always goes to "You". Is it possible to remove them from the logs so you get more accurate numbers on how much dmg "You" actually does?

This applys to some of the boss abilitys aswell, more specific the second boss in Asura.

**Comment by Cavok7** [comment]
You can do this inside ACT, under Ability Redirect in options.

![act-bleed-redirect](https://cloud.githubusercontent.com/assets/9138397/17114715/18810526-527e-11e6-89d0-e06b3714e049.png)

**Comment by chimiko** [comment]
Thanks a bunch! I'm closing this one.
