### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Ask1n** [ravahn/BnS_ACT_Plugin#2]
Hello, your plugin doesnt show the damage over 10k. Will you fix it somehow?

dmg >10k recorded in the eror log

```
> Error [LogParse.BeforeLogLineRead] System.FormatException: Входная строка имела неверный формат.    в System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)    в System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)    в BNS_ACT_Plugin.LogParse.BeforeLogLineRead(Boolean isImport, LogLineEventArgs logInfo) [23:17:48.121]  Terracotta General received 14,072 Critical damage from Onimidori&apos;s Lightning Draw.
> Unhandled Line: [23:17:48.121]  Terracotta General received 14,072 Critical damage from Onimidori&apos;s Lightning Draw.
```

very useful plugin, I hope you can correct this error =)

**Comment by ravahn** [comment]
This looks like bug, thanks for reporting it!

I think the problem is that my code is not properly interpreting the comma as a thousands separator because of the different locale settings.  I'll manually remove the comma, since it seems like BnS is not using the local PC's locale.

**Comment by ravahn** [comment]
I just released v.0.2.0.0 which may fix this problem.  Can you give it a try and let me know if it is resolved?

**Comment by Ask1n** [comment]
Now everything is working
