### ISSUE TITLE
Windows 10 X64, System.OverflowException

### ISSUE THREAD

**Issue by TechTrooper** [ravahn/BnS_ACT_Plugin#3]
Hi,

The plugin manages to log one or two rows and then breaks.. Keeps looping the same error over and over.
Done so far:
- Tried ACTx86.exe and Advanced Combat Tracker.exe
- Reseted Combat tab in game.
- Reinstalled ACT.

```
14:41:47.331|2B|Rosethorn hit Green Training Dummy for 561 damage.
14:41:47.417|Error [BNS_Log.Scan] System.OverflowException: Arithmetic operation resulted in an overflow.    at System.IntPtr..ctor(Int64 value)    at BNS_ACT_Plugin.LogWriter.Scan()14:41:48.430|Error [BNS_Log.Scan] System.OverflowException: Arithmetic operation resulted in an overflow.    at System.IntPtr..ctor(Int64 value)    at BNS_ACT_Plugin.LogWriter.Scan
```

**Comment by AdrienSeon** [comment]
Same problem on my end but for me it doesn't even log one line.
ACT is logging these errors as soon as I launch the client.

Here's attach my log file if you want to look into it.

Thanks for your plugin anyways, hope you'll be able to fix the win10 64 error !

[combatlog_2016-05-01.txt](https://github.com/ravahn/BnS_ACT_Plugin/files/244103/combatlog_2016-05-01.txt)
