### ISSUE TITLE
new update blade and soul

### ISSUE THREAD

**Issue by Ask1n** [ravahn/BnS_ACT_Plugin#4]
the server put the update and now the program does not display the damage

**Comment by aRkker** [comment]
It is not actively maintained as the front page says. Someone should find the offsets for the new one though

**Comment by KanBiiru** [comment]
Is there any type of guide how to find the chat log's offsets?

**Comment by aRkker** [comment]
I asked the original developer if he had any notes regarding this. If he doesn't, I'll try and find em myself and share what I can find

**Comment by ravahn** [comment]
I received a new offset from a friend and updated the .cs file (not the DLL -that won't work anymore).  Give that a try and let me know if it works.

**Comment by Ask1n** [comment]
Everything works, thank you

**Comment by KanBiiru** [comment]
Thank you and your friend for the new offsets.

Is it possible to ask your friend how he got the offsets if hes willing to share? If we can find the offsets ourselves we could potentially keep the Plugin a live for a little bit longer if we aren't too savvy.

**Comment by chimiko** [comment]
Is it possible to make a new release since i have no clue how to convert a .cs into .dll?

**Comment by KanBiiru** [comment]
Chimiko, clone the .cs plugin and just add it like normal. It doesn't need to be in a dll format.

**Comment by chimiko** [comment]
Clone it? Mind explaning? Im sure more people are going to come here not knowing what to do =)
If you don't mind that is.

**Comment by KanBiiru** [comment]
Chimiko, you can either use the Github Desktop App and add the repository to clone or the easiest way is right click the BNS_ACT_PLUGINS.cs and click "Save link as" and it should be saved as a .cs.

Alternatively you can copy the code and paste it into a word processing program (Notepad++) and save it as a .cs. Those are the easiest methods.

**Comment by ravahn** [comment]
Regarding a technique to find the memory locations, my friend did not want to disclose his methods, so I will give some suggestions.  When I have tried it previously, I search for unique chat text as Unicode characters using Cheat Engine or other similar software.  Then, I search for pointer references to the memory location that have a similar set of offsets as the current code.  You can find these in the cs file on Github.

Then, I log out and in a few times, and filter out any pointers that become invalid.  It isn't the best technique, but I caution about posting other ideas publicly, such as specific memory signatures, just in case they become too commonplace.

Closing this topic for now.
