### ISSUE TITLE
Patch 4/27/16

### ISSUE THREAD

**Issue by blayde911** [ravahn/BnS_ACT_Plugin#7]
If anyone is able to find the chatlog memory offset for today's patch to get the parser back up and running, it would be much appreciated. Thanks in advance. 

If anyone has any tips or guides on how to find the memory offsets specifically for the chat log I'd be happy to give it a try. I had no luck doing it with cheat engine when the last patch hit. I'm pretty much a noob though, I can find easy values like hp, attack power, etc (all useless, ofc) but not the chat log.

**Comment by ravahn** [comment]
A new offset was contributed this morning, so I updated the .cs file.  Please try downloading it and see if it works now.
