### ISSUE TITLE
Patch 5/4/2016

### ISSUE THREAD

**Issue by anonaut** [ravahn/BnS_ACT_Plugin#8]
Hey,

they introduced a new patch with an new offset. any chance you could get the updated offset?

thanks in advance
regards,
Mako

**Comment by chimiko** [comment]
Would love to get a hold of the new offset aswell.

**Comment by ravahn** [comment]
I don't currently have the ability to find the offset, so I need to rely on someone else to find and post / email it.  Then I'll update the plugin file.

**Comment by ravahn** [comment]
A kind user contributed a patch with the new offset a couple days ago.  I apologize for the delay, it's been merged now, and hopefully the plugin now works.
